runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /kapwa
  static_files: www/kapwa.html
  upload: www/kapwa.html

- url: /salazar
  static_files: www/salazar_poem.html
  upload: www/salazar_poem.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
